#!/bin/bash -xe

if [ $# -lt 1 ]; then
    (>&2 echo "You need to provide at least one file")
    exit
fi

IFS='.' read -ra PARTS <<< "$1"

clang "$1" ~/PolyJIT_Build/polli-prefix/src/polli-build/lib/libpjit.so -o "${PARTS[0]}.out"
