#!/bin/bash -xe

if [ $# -lt 1 ]; then
    (>&2 echo "You need to provide at least one file")
    exit
fi

IFS='.' read -ra PARTS <<< "$1"

opt -S -load LLVMPolyJIT.so -profileScopDetection "$1" > "${PARTS[0]}InstrumentedScopDetection.ll"
opt -S -load LLVMPolyJIT.so -profileScopPass "$1" > "${PARTS[0]}InstrumentedScopPass.ll"
