#!/bin/bash -x

if [ $# -lt 1 ]; then
    (&>2 echo "You need to provide at least one file")
    exit
fi

IFS='.' read -ra PARTS <<< "$1"

opt -load LLVMPolly.so -polly-ast -analyze -q "$1" -polly-process-unprofitable
